select
    ID,
    PMPERMITID as PM_PERMIT_ID,
    PERMIT_NUMBER,
    PARCEL_NUMBER,
    ADDRESS,
    CITY,
    STATE,
    ZIPCODE,
    PERMIT_STATUS,
    WORK_CLASS,
    PERMIT_TYPE,
    DESCRIPTION,
    COUNCIL_DISTRICT,
    _LOAD_DATE,
    to_timestamp_tz(_LAST_EDIT_DATE, 3) as LAST_UPDATED
from {{ source("PASADENA_AGOL", "EATON_FIRE_REBUILD_PERMITS") }}
