# Project settings
name: caldata_ddrc_pipelines
version: "1.0.0"
config-version: 2

flags:
  send_anonymous_usage_stats: false
  use_colors: true
  warn_error: false

# This setting configures which "profile" dbt uses for this project.
profile: caldata_ddrc_pipelines

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - target
  - dbt_packages

models:
  caldata_ddrc_pipelines:
    staging:
      +database: "{{ env_var('DBT_TRANSFORM_DB', 'TRANSFORM_DDRC_DEV') }}"
      epa:
        +schema: epa
        +materialized: view

    intermediate:
      +database: "{{ env_var('DBT_TRANSFORM_DB', 'TRANSFORM_DDRC_DEV') }}"
      epa:
        +schema: epa
        +materialized: view

    marts:
      +materialized: table
      +database: "{{ env_var('DBT_ANALYTICS_DB', 'ANALYTICS_DDRC_DEV') }}"
      epa:
        +schema: epa
        +materialized: table
      summary:
        +schema: summary
        +materialized: table
        