name: cleanup-tests
on:
  pull_request:
    types:
      - closed

env:
  DBT_PROFILES_DIR: transform/ci
  DBT_RAW_DB: RAW_DDRC_PRD
  DBT_ANALYTICS_DB: ANALYTICS_DDRC_DEV
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_DEV }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_ROLE: TRANSFORMER_DDRC_DEV
  SNOWFLAKE_WAREHOUSE: TRANSFORMING_XS_DDRC_DEV
  SNOWFLAKE_DATABASE: TRANSFORM_DDRC_DEV
  SNOWFLAKE_SCHEMA: GH_CI_PR_${{ github.event.number }}

jobs:
  cleanup-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-root
      - name: Cleanup after tests
        run: |
          poetry run python -m jobs.utils.drop_schemas_with_prefix $SNOWFLAKE_DATABASE $SNOWFLAKE_SCHEMA
          poetry run python -m jobs.utils.drop_schemas_with_prefix $DBT_ANALYTICS_DB $SNOWFLAKE_SCHEMA
