name: nightly
on:
  push:
    branches: [load-assessment-data]

permissions:
  contents: write

env:
  SNOWFLAKE_DATABASE: RAW_DDRC_PRD
  SNOWFLAKE_ROLE: LOADER_DDRC_PRD
  SNOWFLAKE_WAREHOUSE: LOADING_XS_DDRC_PRD
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_PRD }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_PRD }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
      - name: Install dependencies
        run: |
          poetry install
      - name: Run assessment job
        run: |
          poetry run python -m jobs.load_la_fire_assessment
