name: pipeline
on:
  schedule:
    # Run a main hourly job
    - cron: "27 * * * *"
  # Also allow for manual triggers
  workflow_dispatch:

env:
  SNOWFLAKE_PRIVATE_KEY: |
    ${{ github.ref_name =='main' && SECRETS.SNOWFLAKE_PRIVATE_KEY_PRD || SECRETS.SNOWFLAKE_PRIVATE_KEY_DEV }}
  SNOWFLAKE_USER: ${{ github.ref_name =='main' && SECRETS.SNOWFLAKE_USER_PRD || SECRETS.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Load data
        env:
          SNOWFLAKE_ROLE: ${{ github.ref_name =='main' && 'LOADER_DDRC_PRD' || 'LOADER_DDRC_DEV' }}
          SNOWFLAKE_DATABASE: ${{ github.ref_name =='main' && 'RAW_DDRC_PRD' || 'RAW_DDRC_DEV' }}
          SNOWFLAKE_WAREHOUSE: ${{ github.ref_name =='main' && 'LOADING_XS_DDRC_PRD' || 'LOADING_XS_DDRC_DEV' }}
        run: |
          uv run python -m jobs.load_malibu_permitting
