name: tests
on: pull_request

env:
  DBT_PROFILES_DIR: transform/ci
  DBT_RAW_DB: RAW_DDRC_PRD
  SNOWFLAKE_PRIVATE_KEY: ${{ SECRETS.SNOWFLAKE_PRIVATE_KEY_DEV }}
  SNOWFLAKE_USER: ${{ SECRETS.SNOWFLAKE_USER_DEV }}
  SNOWFLAKE_ACCOUNT: ${{ SECRETS.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_ROLE: TRANSFORMER_DDRC_DEV
  SNOWFLAKE_WAREHOUSE: TRANSFORMING_XS_DDRC_DEV
  SNOWFLAKE_DATABASE: TRANSFORM_DDRC_DEV
  SNOWFLAKE_SCHEMA: GH_CI_PR_${{ github.event.number }}

jobs:
  build-models:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Build dbt project
        run: |
          uv run dbt deps --project-dir transform
          uv run dbt build --project-dir transform
          uv run dbt run-operation validate_all_schemas --project-dir transform
